### ISSUE TITLE
[Lisboa] Web Developer na ClaraNet Portugal

### ISSUE THREAD

**Issue by AlexClaranetPortugal** [frontend-pt/vagas#66]
## Descrição da vaga
Posição de Senior Web Developer para a ClaraNet UK. É uma vaga para um time de engenharia do Reino Unido que atua com Pesquisa e Desenvolvimento e que está com um projeto grande de desenvolvimento de produtos para acelerar websites e evitar ataques DDoS. Essa vaga é baseada em Lisboa e tem como requisito inglês fluente para o dia-a-dia pois o time é composto por profissionais de toda a Europa. Arcamos com os custos de visto e transição do profissional. Avaliamos tanto profissionais com boa bagagem técnica em Front-end VueJS quanto profissionais com perfil mais Web Fullstack (skills em Python).
Esse movimento de buscar profissionais aqui no Brasil tem se intensificado ainda mais nos últimos tempos devido às resoluções de LGPD da UE que dizem que um profissional que esteja trabalhando para uma empresa européia precisa estar baseado em um país europeu devido a questões de segurança da informação.
Quer morar no segundo país mais seguro da União Européia (e quarto mais seguro do mundo)? Quer ter qualidade de vida e um trabalho que te expõe a países e empresas de toda a Europa? Sim, eu sei, pode estar soando muito como uma propaganda boa demais pra ser verdade (hahah), mas falo por experiência própria. Aconteceu comigo! Fui contratado (para área de Talent, claro xD ) e dessa mesma forma. Além de te contar tudo sobre a atuação e vaga posso te contar também como está sendo minha experiência pessoal com essa transição.

## Local

Lisboa - atuação remota/híbrida mas baseado em Lisboa

## Benefícios

- Plano de saúde
- Auxílio para transição (hospedagem)
- Custos do visto
- Custos da hospedagem inicial
- Vale-Refeição

## Requisitos

**Obrigatórios:**
Fluent english
- Degree in Computer Science or Information Systems and / or a relevant experience in your industry showing career progression and increasing responsibility in line with a constantly expanding skill set.
- ~3 years of web application development experience, producing standards compliant HTML5, CSS and JS and VueJS
- ~3 years of experience working in a Linux/Unix environment.
- Ability to produce reliable, user driven, well-tested, high-quality code.
- Experience in working with software revision control systems (preferably Git).
- Familiar with, or experience in systems driving continuous integration and continuous deployment (e.g. Jenkins)
- Experience implementing High Availability (HA) and distributed systems/platform design.
- Good understanding of modern computer networking, including IPv6.
- Good understanding of HTTP, DNS and SQL

**Desejáveis:**
- Experience of writing software in Python.

**Diferenciais:**
- Experience with Python.

## Contratação

CLT (equivalente modelo portugues)

## Nossa empresa

A ClaraNet tem mais de 2.500 colaboradores em 10 países (Reino Unido, Portugal, Brasil, França, Alemanha, Holanda, Espanha, Itália, Suíça e USA), 24 escritórios e 45 datacenters, dos quais 2 em Portugal. Você terá exposição a projetos e empresas em toda a Europa e uma progressão de carreira que te permitirá crescer de uma forma exponencial quando comparado ao mercado brasileiro.

## Como se candidatar

Por favor envie um email para alexander.giffoni@pt.clara.net com seu CV anexado e eu te retorno para conversarmos! 
Se quiser, pode me add no LinkedIn também ( https://www.linkedin.com/in/alexgiffoni/ )

## Tempo médio de feedbacks

Eu respondo os e-mails e mensagens no exato momento em que os vejo. Me manda uma mensagem!

## Labels

- Lisboa
- CLT
- Sênior
- English

**Comment by Guedesou** [comment]
## Alex, sua história me deixou muito impactado positivamente!🤩
 Há um ano e pouco meu irmão foi embora morar com meu pai em Lourinhã-PT e, em conversa, ele sempre evidencia o quanto está feliz. Obrigado por abrir estas possibilidades para nós. Irei me aplicar com toda a certeza. Avante!

**Comment by AlexClaranetPortugal** [comment]
> ## Alex, sua história me deixou muito impactado positivamente!🤩
> Há um ano e pouco meu irmão foi embora morar com meu pai em Lourinhã-PT e, em conversa, ele sempre evidencia o quanto está feliz. Obrigado por abrir estas possibilidades para nós. Irei me aplicar com toda a certeza. Avante!

Que legal!!! Vamos conversar!!

**Comment by italo91206** [comment]
## Awesome opportunity !

Alex, fiquei encantado com a oportunidade. Vocês teriam flexibilidade para aceitar desenvolvedores que tivessem menos tempo de experiência, ou a vaga pede imperativamente um dev sênior ?

Te mandei umas mensagens. Obrigado do mesmo jeito,
forte abraço!
