### ISSUE TITLE
[Porto] Front-End Test Automation Engineer na MINDERA

### ISSUE THREAD

**Issue by letiveiga** [frontend-pt/vagas#71]
## Descrição da vaga
Here at Mindera, we are continuously developing a fantastic team and would love it for you to join us.

Do you have the feeling that you keep breaking everything? Working as a Quality Assurance Engineer at Mindera, you will ensure that high standards are kept throughout the development process and within the product deliverables. You will also have an important role in planning and developing automated test suites.

National and international expected traveling time varies according to project/client and organisational needs: 0%-15% estimated.

## Local
Remote or Office or Hybrid, your choice! Our offices are in Porto, Aveiro and Coimbra.

## Benefícios

- Health Insurance, because health comes first
- Flexible working hours
- Open holidays, take the time you need for yourself
- Profit distribution for everyone
- Mindera Annual Trip, Sports, and sharing groups to connect and have fun!
- Training & conferences, create your own training plan
- Child Care vouchers

#### Diferenciais

- Choose Laptop & Peripherals that best suit your needs
- Hotspot with unlimited usage (PT), for work or Netflix ;)
- We have amazing offices in Porto, Aveiro, and Coimbra if you want to physically connect with minders. Remote is also an option.
- At the offices, we have a wide range of snacks to keep you fed and healthy
- Partnerships with local businesses

## Requisitos

- Agile methodologies such as Scrum and Kanban
- Leading quality assurance processes and functional testing
- Working with Software Engineers to ensure the right levels of test automation are built to your standards
- Being versatile. Times change and with them so do requirements, meaning that you may be asked to switch between projects and, consequently, tech stacks. Hence, although we don’t require a specific knowledge of any language, you are expected to be comfortable with high-level programming, in general. (Java, C#, Node.js, Python, etc)
- Testing web applications
- Using source control systems (preferably Git)
- Breaking things and finding problems!
- Knowing how web applications are used by customers and how that translates into what needs to be tested.
- Designing test scenarios, scripts or procedures that fit with the concepts of Test Automation and Continuous Delivery
- Creating resilient automated test suites to exercise Web and Mobile applications with tools like Selenium, Selenide, Cypress, Playwright, Nighwatch.js, etc.
- Being self-driven and working with little supervision towards a common team or company purpose.
- Being motivated to keep learning about test automation

**What you will be doing**

- Validating that what you'll be delivering, as a team, meets the business expectations all the way to, and including, Production
- Continuously find ways to improve the quality of the product
- Implementing mechanisms to mitigate regressions as much as possible, while continuously validating the quality of what's being delivered
- Evangelize quality standards in the team! Quality is the responsibility of absolutely everyone, but you're there to make sure they don't forget :)
- Be the advocate the user (and the business) needs! Your input is invaluable to providing the most user-friendly experience possible
- Actively participate and contribute to solution designs

## Contratação
Full-time

## Nossa empresa
At Mindera we use technology to build products we are proud of, with people we love 💛 

Software Engineering Applications, including Web and Mobile, are at the core of what we do at Mindera 💻 

We partner with our clients, to understand their products and deliver high-performance, resilient and scalable software systems that create an impact in their users and businesses across the world 🌐 

You get to work with a bunch of great people, where the whole team owns the project together.

Our culture reflects our lean and self management attitude. We encourage our colleagues to take risks, make decisions, work in a collaborative way and talk to everyone to enhance communication.

We are proud of our work and we love to learn all and everything while navigating through an Agile, Lean and collaborative environment ⭐ 

Check out our [Blog](http://mindera.com/blog) and our [Handbook](http://bit.ly/MinderaHandbook)!

Our offices are located: Porto, Aveiro e Coimbra -Portugal 🇵🇹 | Leicester - UK 🇬🇧 | San Diego, San Francisco - USA 🇺🇸  | Chennai, 
 Bengaluru - India 🇮🇳  | Cluj-Napoca - Romania 🇷🇴  | Blumenau -Brazil 🇧🇷 

## Como se candidatar
Please send an email with your CV to [scout@mindera.com](mailto:scout@mindera.com)

## Tempo médio de feedbacks
We normally respond within a week, our max is 14 days.

## Labels
- Pleno
- Remoto
- Sênior

**Comment by letiveiga** [comment]
You can check in our website too: https://mindera.com/jobs?roles=2

**Comment by carolinaacc** [comment]
Check out the animated version of our handbook on our YouTube channel: https://youtu.be/7teByAHNp7U

**Comment by letiveiga** [comment]
You can check in our website too: https://mindera.com/jobs?roles=2

**Comment by letiveiga** [comment]
You can check in our website too: https://mindera.com/jobs?roles=2
